# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: socialparking
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27018:27017
    volumes:
      - mongo-volume:/data/db
    networks:
      - internal
    
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - internal
      
  illegalparking:
    image: adikinzor/socialparkingillegalevent
    ports:
      - 8080:8080
    networks:
      - internal
    depends_on:
      - mongo

  parking_lots:
    build: adikinzor/socialparkinglots
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports: 
      - 5000:5000
    networks:
      - internal
    depends_on:
      - mongo
      
  apigateway:
    image: adikinzor/socialparkingapigw
    ports:
      - 8086:8086
    networks:
      - internal
    depends_on:
      - mongo
      - illegalparking
      - parking_lots
    
volumes:
  mongo-volume:
  
networks:
  internal:
