server.port: 8086

spring.data.mongodb.uri: "mongodb://root:example@localhost:27018/socialparking?authSource=admin"

# Properties used in application
signature.secret: "Celmaimaresecret"
illegalparkingserver.host: "http://localhost:8080"
parkinglotserver.host: "http://localhost:5000"
app.firebase-configuration-file: "firebase/big-data-2c769-firebase-adminsdk-85d26-2a0274f347.json"
#logging.level.root: DEBUG