server.port: 8086

spring.data.mongodb.uri: "mongodb://root:example@mongo:27017/socialparking?authSource=admin"

# Properties used in application
signature.secret: "Celmaimaresecret"
illegalparkingserver.host: "http://illegalparking:8080"
parkinglotserver.host: "http://parking_lots:5000"
#logging.level.root: DEBUG